- name: Deploy Sample Application
  hosts: Host
  tasks:
    - name: Install all required dependencies
      raw: apt update && apt upgrade -y && apt install python3 g++ make -y

- name: Docker install
  hosts: Host
  become: true
  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

- name: Test Docker-Compose
  hosts: Host
  tasks:

  - name: Copy docker-compose files from src to dest
    copy:
      src: /root/Test-Sample-Application/getting-started/app
      dest: /tmp
  - name: Run docker-compose
    docker_compose:
      project_src: /tmp/app
      state: present
